### PR TITLE
Specify pi model and add pi3b+

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by Botspot** [comment]
If we are specific with the Pi model letters, would that not mean that we have to add the Pi3A+?

In my opinion, it makes more sense to say "Pi3", than to expand it to "Pi3B/Pi3B+/Pi3A+"

**Comment by mobilegmYT** [comment]
I'm not sure it works with pi3a, since it's nowhere to be found in the official wor flasher but pi3b and pi3b+ is

**Comment by Botspot** [comment]
> I'm not sure it works with pi3a, since it's nowhere to be found in the official wor flasher but pi3b and pi3b+ is

Then why did mariob add CM3 to the list?

**Comment by mobilegmYT** [comment]
?

**Comment by Botspot** [comment]
I think that changing the names of the fields is unnecessary tnd for the Pi3, takes up more space than necessary.
If you have a Pi3B+, you will recognize that that goes into the same category as "Pi3".

**Pull request closed without merging**
